//using System;
//using System.Collections.Generic;
//using System.IO;
//using System.Reflection;
//using System.Text;
//using Aspose.Pdf;
//using Aspose.Pdf.Facades;

//namespace Finastra.Hackathon.Platform
//{
//    public class HtmlToPDFRenderer
//    {
//        public byte[] ToPDF(IReportModel model)
//        {
//            var documentTitle = "Document Title";

//            var options = new HtmlLoadOptions
//            {
//                PageInfo =
//                {
//                    Width = PageSize.A4.Width,
//                    Height = PageSize.A4.Height,
//                    Margin = {Top = 35, Bottom = 40, Right = 35, Left = 35}
//                }
//            };

//            Func<string, string> getManifestResource = s =>
//            {
//                using (var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(s))
//                {
//                    using (var reader = new StreamReader(stream))
//                    {
//                        return reader.ReadToEnd();
//                    }
//                };
//            };

//            Action<Document, string> addReportHeader = (pdf, title) =>
//            {
//                var stamp = new TextStamp(title)
//                {
//                    TopMargin = 15,
//                    LeftMargin = 25,
//                    HorizontalAlignment = HorizontalAlignment.Left,
//                    VerticalAlignment = VerticalAlignment.Top,
//                    Opacity = 0.6f,
//                };

//                stamp.TextState.FontSize = 8;

//                foreach (Page page in pdf.Pages)
//                {
//                    page.AddStamp(stamp);
//                }
//            };

//            Action<Document> addCompanyNameFooter = pdf =>
//            {
//                var companyName = "First Bank of Valkyrie";

//                var stampText = String.Format("Generated by {1} on {0}", DateTime.Now.ToString("M/d/yy - h:mm tt"), companyName);

//                var companyStamp = new TextStamp(stampText)
//                {
//                    BottomMargin = 15,
//                    LeftMargin = 25,
//                    HorizontalAlignment = HorizontalAlignment.Left,
//                    VerticalAlignment = VerticalAlignment.Bottom,
//                    Opacity = 0.6f,
//                };

//                companyStamp.TextState.FontSize = 8;

//                foreach (Page page in pdf.Pages)
//                {
//                    page.AddStamp(companyStamp);
//                }
//            };

//            Action<Document> addPageNumberFooter = pdf =>
//            {
//                var pageStamp = new TextStamp("")
//                {
//                    BottomMargin = 15,
//                    RightMargin = 25,
//                    HorizontalAlignment = HorizontalAlignment.Right,
//                    VerticalAlignment = VerticalAlignment.Bottom,
//                    Opacity = 0.6f,
//                };

//                pageStamp.TextState.FontSize = 8;
//                var pageCount = 1;

//                foreach (Page page in pdf.Pages)
//                {
//                    pageStamp.Value = "Page: " + pageCount++;
//                    page.AddStamp(pageStamp);
//                }
//            };

//            Action<Document> addDocumentInfo = pdf =>
//            {
//                var d = new DocumentInfo(pdf)
//                {
//                    Author = "Sycorr",
//                    CreationDate = DateTime.Now,
//                    Title = "First Bank of Valkyrie " + documentTitle,
//                    Subject = "First Bank of Valkyrie " + documentTitle
//                };
//            };

//            Func<string, object, Document> createDocument = (template, model) =>
//            {
//                var html = Platform.RazorEngine.Run(template, model);

//                var buffer = Encoding.UTF8.GetBytes(html);
//                var instream = new MemoryStream(buffer);

//                return new Document(instream, options);
//            };

//            var docs = new List<Document>();
//            docs.Add(createDocument(view, null));

//            var templateId = string.Format("GeneratedPDF_{0}", view);
//            var modelTemplate = getManifestResource(view);
//            Platform.RazorEngine.AddTemplate(templateId, modelTemplate);

//            var d = createDocument(templateId, split);
//            docs.Add(d);

//            using (var doc = new Document())
//            {
//                foreach (var d in docs)
//                {
//                    doc.Pages.Add(d.Pages);
//                }

//                addReportHeader.Invoke(doc, ("First Bank of Valkyrie " + documentTitle).Trim());
//                addCompanyNameFooter.Invoke(doc);
//                addPageNumberFooter.Invoke(doc);
//                addDocumentInfo.Invoke(doc);

//                var privilege = DocumentPrivilege.ForbidAll;
//                privilege.ChangeAllowLevel = 1;
//                privilege.AllowPrint = true;
//                privilege.AllowCopy = true;

//                var fileSecurity = new PdfFileSecurity(doc);
//                fileSecurity.SetPrivilege(privilege);

//                using (var outstream = new MemoryStream())
//                {
//                    doc.Save(outstream);
//                    return outstream.GetBuffer();
//                }
//            }
//        }
//    }

//}
